Add entrypoints to the build_product script

diff --git a/build_product b/build_product
--- a/build_product
+++ b/build_product
@@ -79,7 +79,8 @@ _arg_bash_scripts="on"
 _arg_datastream_only="off"
 _arg_profiling="off"
 _arg_log="off"
-
+_arg_thin_datastream="off"
+_arg_rule_id="off"
 
 print_help()
 {
@@ -93,6 +94,8 @@ print_help()
 	printf '\t%s\n' "--derivatives, --no-derivatives: Also build derivatives of products if applicable (off by default)"
 	printf '\t%s\n' "--ansible-playbooks, --no-ansible-playbooks: Build Ansible Playbooks for every profile (on by default)"
 	printf '\t%s\n' "--bash-scripts, --no-bash-scripts: Build Bash remediation scripts for every profile (on by default)"
+	printf '\t%s\n' "-t, --thin, --no-thin: Build thin data streams for each rule. Do not build any of the guides, tables, etc (off by default)"
+	printf '\t%s\n' "-r, --rule-id: Rule ID: Build a thin data stream with the specified rule. Do not build any of the guides, tables, etc (off by default)"
 	printf '\t%s\n' "-d, --datastream-only, --no-datastream-only: Build the data stream only. Do not build any of the guides, tables, etc (off by default)"
 	printf '\t%s\n' "-p, --profiling, --no-profiling: Use ninja and call the build_profiler.sh util (off by default)"
 	printf '\t%s\n' "-l, --log, --no-log: Logs all debugging messages (off by default)"
@@ -147,6 +150,17 @@ parse_commandline()
 				_arg_debug="on"
 				test "${1:0:5}" = "--no-" && _arg_debug="off"
 				;;
+			-r|--rule-id)
+				_arg_rule_id="$2"
+				test $# -lt 2 && _arg_rule_id="ALL_RULES"
+				shift
+				;;
+			--rule-id=*)
+				_arg_rule_id="${_key##--oval=}"
+				;;
+			-r*)
+				_arg_rule_id="${_key##-r}"
+				;;
 			--no-derivatives|--derivatives)
 				_arg_derivatives="on"
 				test "${1:0:5}" = "--no-" && _arg_derivatives="off"
@@ -158,6 +172,18 @@ parse_commandline()
 			--no-bash-scripts|--bash-scripts)
 				_arg_bash_scripts="on"
 				test "${1:0:5}" = "--no-" && _arg_bash_scripts="off"
+				;;
+			-t|--no-thin|--thin)
+				_arg_thin_datastream="on"
+				test "${1:0:5}" = "--no-" && _arg_thin_datastream="off"
+				;;
+			-t*)
+				_arg_thin_datastream="on"
+				_next="${_key##-d}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
 				;;
 			-d|--no-datastream-only|--datastream-only)
 				_arg_datastream_only="on"
@@ -309,7 +335,7 @@ set_no_derivatives_options() {
 }
 
 set_explict_build_targets() {
-	if test "$_arg_datastream_only" = on ; then
+	if test "$_arg_datastream_only" = on || test "$_arg_thin_datastream" = on || test "$_arg_rule_id" != off ; then
 		for chosen_product in "${_arg_product[@]}"; do
 			EXPLICIT_BUILD_TARGETS+=("generate-ssg-$(to_lowercase "$chosen_product")-ds.xml")
 		done
@@ -413,6 +439,21 @@ else
 	CMAKE_OPTIONS+=("-DSSG_LOG:BOOL=OFF")
 fi
 
+
+if [ "$_arg_rule_id" != off ] ; then
+	_arg_thin_datastream="on"
+	CMAKE_OPTIONS+=("-DSSG_THIN_DS_RULE_ID:STR=${_arg_rule_id}")
+elif [ "$_arg_thin_datastream" == on ] && [ "$_arg_rule_id" == off ] ; then
+	CMAKE_OPTIONS+=("-DSSG_THIN_DS_RULE_ID:STR=ALL_RULES")
+else
+	CMAKE_OPTIONS+=("-DSSG_THIN_DS_RULE_ID:STR=off")
+fi
+
+if [ "$_arg_thin_datastream" = on ] ; then
+	CMAKE_OPTIONS+=("-DSSG_THIN_DS:BOOL=ON")
+else
+	CMAKE_OPTIONS+=("-DSSG_THIN_DS:BOOL=OFF")
+fi
 
 set -e
 [ -d build ] || mkdir build
