Add log option to stcript ./build_product

diff --git a/build_product b/build_product
--- a/build_product
+++ b/build_product
@@ -78,6 +78,7 @@ _arg_ansible_playbooks="on"
 _arg_bash_scripts="on"
 _arg_datastream_only="off"
 _arg_profiling="off"
+_arg_log="off"
 
 
 print_help()
@@ -94,6 +95,7 @@ print_help()
 	printf '\t%s\n' "--bash-scripts, --no-bash-scripts: Build Bash remediation scripts for every profile (on by default)"
 	printf '\t%s\n' "-d, --datastream-only, --no-datastream-only: Build the data stream only. Do not build any of the guides, tables, etc (off by default)"
 	printf '\t%s\n' "-p, --profiling, --no-profiling: Use ninja and call the build_profiler.sh util (off by default)"
+	printf '\t%s\n' "-l, --log, --no-log: Logs all debugging messages (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
 	printf '\nEnvironment variables that are supported:\n'
 	printf '\t%s\n' "ADDITIONAL_CMAKE_OPTIONS: Whitespace-separated string of arguments to pass to CMake."
@@ -179,6 +181,18 @@ parse_commandline()
 				if test -n "$_next" -a "$_next" != "$_key"
 				then
 					{ begins_with_short_option "$_next" && shift && set -- "-p" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+				fi
+				;;
+			-l|--no-log|--log)
+				_arg_log="on"
+				test "${1:0:5}" = "--no-" && _arg_log="off"
+				;;
+			-l*)
+				_arg_log="on"
+				_next="${_key##-l}"
+				if test -n "$_next" -a "$_next" != "$_key"
+				then
+					{ begins_with_short_option "$_next" && shift && set -- "-l" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
 				fi
 				;;
 			-h|--help)
@@ -391,6 +405,13 @@ if [ "$_arg_bash_scripts" = off ] ; then
 fi
 EXPLICIT_BUILD_TARGETS=()
 set_explict_build_targets
+
+if [ "$_arg_log" = on ] ; then
+	CMAKE_OPTIONS+=("-DSSG_LOG:BOOL=ON")
+else
+	CMAKE_OPTIONS+=("-DSSG_LOG:BOOL=OFF")
+fi
+
 
 set -e
 rm -rf build/*
